/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package _JavaGradle;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Welcome.....");
        return true;
    }
}
